# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty


os:
  - linux

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./ci/travis.install.py

install:
  - ./ci/travis.install.py

script:
  - git clone https://github.com/paxtibi/paxjson.git     packages/paxjson
  - git clone https://github.com/paxtibi/paxlogging.git  packages/paxlogging
  - git clone https://github.com/paxtibi/paxhttp.git     packages/paxhttp
  - lazbuild --add-package packages/paxhttp/pck/paxhttp_package.lpk packages/paxjson/pck/paxjson_package.lpk packages/paxlogging/pck/paxlogging_package.lpk
#  - lazbuild --build-ide="normal-ide"
  - lazbuild pck/jsonserver.lpi
  
notifications:
  email:
    on_success: false
    on_failure: change
